### ISSUE TITLE
User feedback when point falls into the ocean or hole

### ISSUE THREAD

**Issue by vanbremer** [glowabio/geofresh#35]

**Comment by vanbremer** [comment]
Users need to be notified if no sub-catchment ID is returned from query. Points should be discarded from further queries for now.

**Comment by vanbremer** [comment]
If points do not overlap with regional unit polygon reg_id will be empty --> check table for null values and notify user

**Comment by tomitho** [comment]
Almost fixed!
So far users are notified when points are not located in a sub-catchment. This either results from that points are located in the ocean or inside a lake. 
Lake Ids still need to be integrated. Then lake information needs to be returned when points fall into lakes.
