### ISSUE TITLE
Add information on year to land use and climate data

### ISSUE THREAD

**Issue by vanbremer** [glowabio/geofresh#49]

**Comment by domisch** [comment]
Could you please add the following to the column header, thanks :-)
"Bioclimatic variables for 1981-2010"
"Annual landcover for 2018"

...obviously the data should stem from the same timeframe, but the new climate data has not yet been released

**Comment by vanbremer** [comment]
In the Documentation tab add the data citation for CHELSA v2.1:
Karger, D.N., Conrad, O., Böhner, J., Kawohl, T., Kreft, H., Soria-Auza, R.W., Zimmermann, N.E., Linder, H.P. & Kessler, M. (2021) Climatologies at high resolution for the earth’s land surface areas. EnviDat. https://doi.org/10.16904/envidat.228.v2.1

**Comment by vanbremer** [comment]
"Soil data for 2016"
"Hydrography90m stream topology"
